version: '3'
services:
#MongoDB services
  mongodb:
    container_name: db_container
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db

#Node API service
  api:
    build: .
    ports: 
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: my_db
    depends_on:
      - mongodb

    
volumes:
  mongodb: {}

